spring:
  application:
    name: '@project.artifactId@'
  profiles:
    active: ${profile}
  security:
    user:
      name: user
      password: user
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:54032/postgres"
    username: "compose-postgres"
    password: "compose-postgres"
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 8081
  servlet:
    context-path: /stockManagementApi/v1/

constants:
  error:
    stockDetailNotFoundException:
      code: STOCK_DETAILS_NOT_FOUND
      message: 'Stock data is not present.'
    constraintViolationException:
      code: INVALID_DETAILS
      message: 'Invalid details provided in the request.'

#swagger
swagger.api:
  title: 'PayConfig Stock Management Api'
  description: 'This service enables to manage stocks'
  version: 1
  apiType: private
  defaultResponseMessage: false
  basePackage: com.payconfiq.stockmanagement
  contact:
    email: anurag.r.mishra@protonmail.com
    teamName: Payconiq StockManagement