version: '2'

services:
  app:
    image: 'stockmanagementapi-postgres:latest'
    ports:
      - "8081:8081"
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SECURITY_USER_NAME=user
      - SPRING_SECURITY_USER_PASSWORD=user

  db:
    image: 'postgres:13.1-alpine'
    restart: always
    ports:
      - "5432:5432"
    container_name: postgresdb
    volumes:
      - ./data-postgres:/var/lib/postgresql/data
      # copy the sql script to create tables
      #- ./schema-postgres.sql:/docker-entrypoint-initdb.d/schema-postgres.sql
      #- ./data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres